### PR TITLE
Fix iOS build error

### PR DESCRIPTION
**Pull request by sanak**
@moovida, @mbasa
This is another PR instead of #211, but checking this is helpful on your environment.
(Thanks @mbasa for #211, because without the PR, I couldn't find what changes are necessary. 🙇‍♂️)

## Problem

When I tried to debug  app on iOS device with current `master` branch, I encountered the following issue.
ios-build-error-on-master

## Solution

From referring #211 diff (https://github.com/geopaparazzi/smash/pull/211/files) and background_locator_2(fixed) Wiki (https://github.com/Yukams/background_locator_fixed/wiki/Setup-IOS-in-case-of-Object-C-project), I tried as follows.

1. Upgrade minimum iOS version from 9.0 to 11.0
   - diff: https://github.com/geopaparazzi/smash/commit/ad4b105e7d28ede01d9983d8088a1d919c77dc56
2. Delete the following files temporarily.
   - Podfile.lock
   - Pods folder
   - Runner.xcworkspace
3. Run the command `pod install`, then add updated `Podfile.lock` and `Runner.xcodeproj`.
   - diff: https://github.com/geopaparazzi/smash/commit/8701c28e5f85ec6b450d65ea8dbc97ac9d786f56
4. Fix ios `AppDelegate.swift` - `background_locator_2` package name.
   - diff: https://github.com/geopaparazzi/smash/commit/789a5650d626440b89334df77431b95de4012271
5. Restore No.2 temporary deleted files.

With above changes, build was finished successfully (with changing signing part on Xcode), but when I launch the app, I encountered the following error.
```
2023-01-07 18:14:52.798923+0900 Runner[2237:1193484] flutter: w: Manage External Storage permission is not granted.
```
smash-ios-ext

With the following code side changes (comment `PERMISSIONS.MANAGEEXTSTORAGE` part), I could launch the app, and there seems to be no problem, but is this correct way on iOS ?
```diff
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -375,8 +375,8 @@ Future<String?> handleStoragePermission(BuildContext context) async {
   if (!SmashPlatform.isDesktop()) {
     var storagePermission = await PermissionManager()
         .add(PERMISSIONS.STORAGE)
-        .add(
-            PERMISSIONS.MANAGEEXTSTORAGE) // TODO comment this for store release
+        // .add(
+        //     PERMISSIONS.MANAGEEXTSTORAGE) // TODO comment this for store release
         .check(context);
     if (!storagePermission) {
       return SL.of(context).main_storagePermissionIsMandatoryToOpenSmash;
```

Note that here is my environment.
```sh
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.74.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

Thanks,

### CODE REVIEW

**Comment by moovida** [comment]
Hi @sanak , I have not yet tested this PR, but I should have fixed the permission issue, which was affecting in devel mode both IOS and older Android devices. Check if it solves the MANAGEEXTSTORAGE issue you are having.

**Comment by moovida** [comment]
Also, I am not sure, does this superseed #211 ?

**Comment by sanak** [comment]
> Hi @sanak , I have not yet tested this PR, but I should have fixed the permission issue, which was affecting in devel mode both IOS and older Android devices. Check if it solves the MANAGEEXTSTORAGE issue you are having.

Okay. I haven't tested it on both Debug and Release build on iOS, so I will check it and take a look at the cause more.

> Also, I am not sure, does this superseed https://github.com/geopaparazzi/smash/pull/211 ?

I think so, but @mbasa, are you okay about that ?

**Comment by sanak** [comment]
@moovida (CC: @smellman, @mbasa, @dkastl)
Well, I think that this PR (and former #211) changes are covered by #216 and #217, so I close this PR.

@smellman Thanks a lot !

@mbasa Could you close PR #211 side ?

Thanks,

**Pull request closed without merging**
