### PR TITLE
Fix/update mobile settings

### PR DESCRIPTION
**Pull request by mbasa-georepublic**
@moovida I was having difficulties deploying to an iPhone with IOS 16.2 using the latest Xcode so I totally rebuilt the ios directory. I updated as well the android.

This might be useful. It will be necessary though to change my credentials to yours in Xcode. 

Regards.

### CODE REVIEW

**Comment by moovida** [comment]
Hi @mbasa , while I am all in with upgrading the build, you removed also vital files, as for example the zenodo parts for the DOI reference and the whole f-droid work in progress (fastlane). :-)

**Comment by mbasa-georepublic** [comment]
Apologies @moovida if I somehow messed things up. Strange though since I spent almost a day making sure that the essential portions of the `master branch` has been incorporated into this branch. 

The iOS seems to be working correctly since I have been using my iPhone these past few days to log my tracks in SMASH, then upload the data into Redmine: 

https://demo.lobsta.io/issues/494
https://demo.lobsta.io/issues/493
https://demo.lobsta.io/issues/492

**Comment by moovida** [comment]
@mbasa-georepublic , I am not sure what you mean. Essential portions are there I assume, but some additional parts have been removed (see my description above). These parts do not have anything to do with the flutter build and should not be removed.

**Comment by smellman** [comment]
@mbasa-georepublic Please close this PR.
It is not need no more.

**Comment by moovida** [comment]
Closing this as of last comment.

**Pull request closed without merging**
